name: Build and Push to ECR on Tag

on:
  push:
    tags:
      - "v*" # Match tags starting with 'v'
    paths:
      - "web-ingestion/app/*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: web-ingestion
      AWS_REGION: us-east-1 # Update with your AWS region
      VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID }}
      VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set Vault environment variables
        run: |
          echo "export VAULT_ROLE_ID=${VAULT_ROLE_ID}" >> $GITHUB_ENV
          echo "export VAULT_SECRET_ID=${VAULT_SECRET_ID}" >> $GITHUB_ENV
          echo "export VAULT_ADDR=${VAULT_ADDR}" >> $GITHUB_ENV

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Create ECR repository if it does not exist
        run: |
          aws ecr describe-repositories --repository-names ${{ env.IMAGE_NAME }} || aws ecr create-repository --repository-name ${{ env.IMAGE_NAME }}
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

      - name: Build, tag, and push image to Amazon ECR
        run: |
          # Build the Docker image and tag it with the desired image tag
          docker build -t $ECR_REGISTRY/${{ env.IMAGE_NAME }}:${{ github.event.ref }} --build-arg VAULT_ROLE_ID=${VAULT_ROLE_ID} --build-arg VAULT_SECRET_ID=${VAULT_SECRET_ID} --build-arg VAULT_ADDR=${VAULT_ADDR} web-ingestion/app/

          # Push the image to Amazon ECR.
          docker push $ECR_REGISTRY/${{ env.IMAGE_NAME }}:${{ github.event.ref }}
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
